"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app -O2
"""

from glob import glob
from setuptools import setup


APP = ['KNetConnect.py']
DATA_FILES = [
    ('images', glob('images/*.png')),
    ('', ['preferences.py'])
]
OPTIONS = {
    'iconfile': 'images/appIcon.icns',
    'argv_emulation': False,
    'plist': {'LSUIElement': 1}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
